CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50),
  attempt ENUM('good','bad'),
  time DATETIME
);
